### ISSUE TITLE
Unable to pull image

### ISSUE THREAD

**Issue by Deepali-Surlikar** [opsgy/loki-rule-operator#11]
When I try to pull image using command docker pull eu.gcr.io/opsgy-com/loki-rule-operator:v0.5.0, it says 

Error response from daemon: pull access denied for eu.gcr.io/opsgy-com/loki-rule-operator, repository does not exist or may require 'docker login': denied: Permission denied for "v0.5.0" from request "/v2/opsgy-com/loki-rule-operator/manifests/v0.5.0".

**Comment by saada** [comment]
Looking at https://console.cloud.google.com/gcr/images/opsgy-com/EU/loki-rule-operator it show this error

```
Project not found or deleted
```

**Comment by Deepali-Surlikar** [comment]
Closing issue as the image is available now.
